name: PR Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches-ignore:
      - 'rc/**'
      - 'main'

jobs:
  pr-workflow:
    uses: AlaskaAirlines/auro-actions/.github/workflows/pull-request.yml@main