name: PR Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches-ignore:
      - 'rc/**'
      - 'main'

jobs:
  action:
    permissions:
      id-token: write  # required for OIDC (npm provenance)
      contents: read
    uses: AlaskaAirlines/auro-actions/.github/workflows/pull-request.yml@dev
    with:
      component: 'devops-component'
    secrets:
      AURO_SURGE_TOKEN: ${{ secrets.AURO_SURGE_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}